/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kursiniopagrprogkodas;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aneta
 */
public class DestytojuLangas extends javax.swing.JFrame {

      Sistema sist = new Sistema();
      DuomenuBaze db =  new DuomenuBaze();
  
      
    /**
     * Creates new form DestytojuLangas
     */
    public DestytojuLangas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        DestytojoID = new javax.swing.JTextField();
        DestytojoVardas = new javax.swing.JTextField();
        DestytojoPavarde = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Prideti = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        destytojoIdSalint = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pasalintiDestytoja = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        lentele = new javax.swing.JTable();
        griztiMygtukas = new javax.swing.JButton();
        isieitMygtuka = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DestytojoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestytojoIDActionPerformed(evt);
            }
        });

        DestytojoVardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestytojoVardasActionPerformed(evt);
            }
        });

        DestytojoPavarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestytojoPavardeActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Vardas");

        jLabel3.setText("Pavardė");

        Prideti.setText("Pridėti dėstytoją");
        Prideti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridetiActionPerformed(evt);
            }
        });

        jLabel4.setText("Prideti dėstytoją");

        jLabel5.setText("Pašalinti dėstytoją");

        destytojoIdSalint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destytojoIdSalintActionPerformed(evt);
            }
        });

        jLabel6.setText("Dėstytojo ID");

        pasalintiDestytoja.setText("Pašalinti");
        pasalintiDestytoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasalintiDestytojaActionPerformed(evt);
            }
        });

        lentele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vardas", "Pavarde"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(lentele);

        griztiMygtukas.setText("Grįžti");
        griztiMygtukas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                griztiMygtukasActionPerformed(evt);
            }
        });

        isieitMygtuka.setText("Išeiti");
        isieitMygtuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isieitMygtukaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DestytojoID, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(103, 103, 103)
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(DestytojoVardas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DestytojoPavarde, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(pasalintiDestytoja))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(destytojoIdSalint, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(Prideti))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(griztiMygtukas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(isieitMygtuka, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DestytojoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestytojoVardas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestytojoPavarde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Prideti)
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destytojoIdSalint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(pasalintiDestytoja)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(griztiMygtukas)
                .addGap(18, 18, 18)
                .addComponent(isieitMygtuka)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DestytojoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestytojoIDActionPerformed
    
    }//GEN-LAST:event_DestytojoIDActionPerformed

    private void PridetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridetiActionPerformed
     String destId = DestytojoID.getText();
     String destVardas = DestytojoVardas.getText();
     String destPavarde = DestytojoPavarde.getText();
           DefaultTableModel destytojuLentele =  (DefaultTableModel) this.lentele.getModel();

        sist.pridetiDestytoja(Integer.parseInt(destId), destVardas, destPavarde);
        db.InsertIntoDestytojai(Integer.parseInt(destId), destVardas, destPavarde);
        
         
           destytojuLentele.addRow(new Object[] {destId, destVardas, destPavarde});
           
       db.dbConnect();
    }//GEN-LAST:event_PridetiActionPerformed

    private void DestytojoVardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestytojoVardasActionPerformed
      
    }//GEN-LAST:event_DestytojoVardasActionPerformed

    private void DestytojoPavardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestytojoPavardeActionPerformed
        
    }//GEN-LAST:event_DestytojoPavardeActionPerformed

    private void pasalintiDestytojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasalintiDestytojaActionPerformed
   String destId = destytojoIdSalint.getText();
   
         DefaultTableModel destytojuLentele =  (DefaultTableModel) this.lentele.getModel();

       
       String code = "DELETE FROM Destytojas WHERE id='"+destId+"'";
          try {
              PreparedStatement statement = db.dbConnect().prepareStatement(code);
              
                statement.execute();
          } catch (SQLException ex) {
              Logger.getLogger(DestytojuLangas.class.getName()).log(Level.SEVERE, null, ex);
          }
            
        
        for (int i = 0; i < destytojuLentele.getRowCount(); i++) {
                if (((String)destytojuLentele.getValueAt(i, 0)).equals(destId)) {
                    destytojuLentele.removeRow(i);
                }
            }
        
    }//GEN-LAST:event_pasalintiDestytojaActionPerformed

    private void destytojoIdSalintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destytojoIdSalintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destytojoIdSalintActionPerformed

    private void griztiMygtukasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_griztiMygtukasActionPerformed
        new  Pradinis().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_griztiMygtukasActionPerformed

    private void isieitMygtukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isieitMygtukaActionPerformed
    System.exit(0);
    }//GEN-LAST:event_isieitMygtukaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DestytojuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DestytojuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DestytojuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DestytojuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DestytojuLangas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DestytojoID;
    private javax.swing.JTextField DestytojoPavarde;
    private javax.swing.JTextField DestytojoVardas;
    private javax.swing.JButton Prideti;
    private javax.swing.JTextField destytojoIdSalint;
    private javax.swing.JButton griztiMygtukas;
    private javax.swing.JButton isieitMygtuka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTable lentele;
    private javax.swing.JButton pasalintiDestytoja;
    // End of variables declaration//GEN-END:variables
}
