/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kursiniopagrprogkodas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aneta
 */
public class GrupiuLangas extends javax.swing.JFrame {
      Sistema sist = new Sistema();
      DuomenuBaze db = new DuomenuBaze();
      

    /**
     * Creates new form GrupiuLangas
     */
    public GrupiuLangas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        PridetiGrupe = new javax.swing.JButton();
        GrupesKodas = new javax.swing.JTextField();
        StojimoMetai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        GrupesID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        StudentoID = new javax.swing.JTextField();
        StudentoVardas = new javax.swing.JTextField();
        StudentoPavarde = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PridetiStudenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lentele = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        lentele2 = new javax.swing.JTable();
        griztiMygtukas = new javax.swing.JButton();
        iseitiMygtukas = new javax.swing.JButton();

        jTextField4.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PridetiGrupe.setText("Pridėti grupę");
        PridetiGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridetiGrupeActionPerformed(evt);
            }
        });

        GrupesKodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrupesKodasActionPerformed(evt);
            }
        });

        StojimoMetai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StojimoMetaiActionPerformed(evt);
            }
        });

        jLabel1.setText("Pridėti grupę");

        jLabel2.setText("Grupės kodas");

        jLabel3.setText("Stojimo metai");

        jLabel4.setText("Pridėti studentą");

        StudentoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentoIDActionPerformed(evt);
            }
        });

        StudentoVardas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentoVardasActionPerformed(evt);
            }
        });

        jLabel5.setText("Grupės kodas");

        jLabel6.setText("Studento ID");

        jLabel7.setText("Studento vardas");

        jLabel8.setText("Studento pavardė");

        PridetiStudenta.setText("Pridėti studentą");
        PridetiStudenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PridetiStudentaActionPerformed(evt);
            }
        });

        lentele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupės kodas", "Stojimo metai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lentele);

        lentele2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupės kodas", "Studento ID", "Studento vardas", "Studento pavardė"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(lentele2);

        griztiMygtukas.setText("Grįžti");
        griztiMygtukas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                griztiMygtukasActionPerformed(evt);
            }
        });

        iseitiMygtukas.setText("Išeiti");
        iseitiMygtukas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iseitiMygtukasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(PridetiGrupe))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(StojimoMetai, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 82, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(GrupesID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StudentoID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StudentoVardas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(StudentoPavarde, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GrupesKodas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addGap(320, 320, 320)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(griztiMygtukas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PridetiStudenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(iseitiMygtukas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GrupesKodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StojimoMetai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PridetiGrupe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentoVardas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentoPavarde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrupesID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(PridetiStudenta)
                .addGap(18, 18, 18)
                .addComponent(griztiMygtukas)
                .addGap(18, 18, 18)
                .addComponent(iseitiMygtukas)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StojimoMetaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StojimoMetaiActionPerformed
       
    }//GEN-LAST:event_StojimoMetaiActionPerformed

    private void PridetiGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridetiGrupeActionPerformed
       String stojimoMetai = StojimoMetai.getText();
       String grupesKodas = GrupesKodas.getText();
       DefaultTableModel grupiuLentele =  (DefaultTableModel) this.lentele.getModel();
        sist.pridetiGrupe(grupesKodas, Integer.parseInt(stojimoMetai));
       db.InsertIntoGrupes(grupesKodas, Integer.parseInt(stojimoMetai));
        grupiuLentele.addRow(new Object[] {grupesKodas, stojimoMetai});
        db.dbConnect();
        
    }//GEN-LAST:event_PridetiGrupeActionPerformed

    private void GrupesKodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrupesKodasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrupesKodasActionPerformed

    private void StudentoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentoIDActionPerformed

    private void StudentoVardasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentoVardasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentoVardasActionPerformed

    private void PridetiStudentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PridetiStudentaActionPerformed
       String grupesKodas = GrupesID.getText();
       String studentoKodas = StudentoID.getText();
       String studentoVardas = StudentoVardas.getText();
       String studentoPavarde = StudentoPavarde.getText();
       
        sist.grupesID(grupesKodas).pridetiStudenta(Integer.parseInt(studentoKodas), studentoVardas, studentoPavarde);
       db.InsertIntoStudentai(grupesKodas, Integer.parseInt(studentoKodas), studentoVardas, studentoPavarde);
       DefaultTableModel studentuLentele = (DefaultTableModel) this.lentele2.getModel();
       
       
        studentuLentele.addRow(new Object[] {grupesKodas, studentoKodas,studentoVardas, studentoPavarde});
    }//GEN-LAST:event_PridetiStudentaActionPerformed

    private void griztiMygtukasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_griztiMygtukasActionPerformed
           new Pradinis().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_griztiMygtukasActionPerformed

    private void iseitiMygtukasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iseitiMygtukasActionPerformed
        System.exit(0);
    }//GEN-LAST:event_iseitiMygtukasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrupiuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrupiuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrupiuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrupiuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrupiuLangas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GrupesID;
    private javax.swing.JTextField GrupesKodas;
    private javax.swing.JButton PridetiGrupe;
    private javax.swing.JButton PridetiStudenta;
    private javax.swing.JTextField StojimoMetai;
    private javax.swing.JTextField StudentoID;
    private javax.swing.JTextField StudentoPavarde;
    private javax.swing.JTextField StudentoVardas;
    private javax.swing.JButton griztiMygtukas;
    private javax.swing.JButton iseitiMygtukas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable lentele;
    private javax.swing.JTable lentele2;
    // End of variables declaration//GEN-END:variables
}
