/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kursiniopagrprogkodas;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Aneta
 */
public class KursuLangas extends javax.swing.JFrame {
    
        Sistema sist = new Sistema();
        DuomenuBaze db = new DuomenuBaze();
        
    /**
     * Creates new form KursuLangas
     */
    public KursuLangas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KursoPavadinimas = new javax.swing.JTextField();
        kursoPavadinimas = new javax.swing.JLabel();
        pridetiKursa = new javax.swing.JButton();
        IseitiMygtukas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lentele = new javax.swing.JTable();
        griztiMygtukas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KursoPavadinimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KursoPavadinimasActionPerformed(evt);
            }
        });

        kursoPavadinimas.setText("Kurso Pavadinimas");

        pridetiKursa.setText("Pridėti");
        pridetiKursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridetiKursaActionPerformed(evt);
            }
        });

        IseitiMygtukas.setText("Išeiti");
        IseitiMygtukas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IseitiMygtukasActionPerformed(evt);
            }
        });

        lentele.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kurso pavadinimas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lentele);

        griztiMygtukas.setText("Grįžti");
        griztiMygtukas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                griztiMygtukasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kursoPavadinimas)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(KursoPavadinimas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pridetiKursa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(IseitiMygtukas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(griztiMygtukas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(kursoPavadinimas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KursoPavadinimas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pridetiKursa))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(griztiMygtukas)
                .addGap(39, 39, 39)
                .addComponent(IseitiMygtukas)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridetiKursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridetiKursaActionPerformed
      String kursoPavadinimas = KursoPavadinimas.getText();
       sist.pridetiKursa(kursoPavadinimas);
       DefaultTableModel kursuLentele =  (DefaultTableModel) this.lentele.getModel();
         db.InsertIntoKursai(kursoPavadinimas);
        kursuLentele.addRow(new Object[] {kursoPavadinimas});
        db.dbConnect();
                                                
    }//GEN-LAST:event_pridetiKursaActionPerformed

    private void KursoPavadinimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KursoPavadinimasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KursoPavadinimasActionPerformed

    private void IseitiMygtukasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IseitiMygtukasActionPerformed
   System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_IseitiMygtukasActionPerformed

    private void griztiMygtukasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_griztiMygtukasActionPerformed
   new Pradinis().setVisible(true);
   this.dispose();
    }//GEN-LAST:event_griztiMygtukasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KursuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KursuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KursuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KursuLangas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KursuLangas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IseitiMygtukas;
    private javax.swing.JTextField KursoPavadinimas;
    private javax.swing.JButton griztiMygtukas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kursoPavadinimas;
    private javax.swing.JTable lentele;
    private javax.swing.JButton pridetiKursa;
    // End of variables declaration//GEN-END:variables
}
